### ISSUE TITLE
Demo Page > Pie chart percentages vs illustration

### ISSUE THREAD

**Issue by TheSpiciestDev** [Misfits-Rebels-Outcasts/Blazor-Dashboard#1]
On the live demo (also in the screenshot in the README.md file) the pie chart data and illustration do not match. There is also an empty, blank space - is this a rendering bug?

**Comment by BlazorDashboard** [comment]
Thanks for pointing out. You are right that it is not matching :) At the moment, the pie chart is still a prototype and I have recently just started to use BuildRenderTree for it to be dynamically generated. Right now, I am looking into making a simple library for reuse in the different charts to be included as part of the same project.
